name: "build-and-test"
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

        # Catch2 installed by default
      - name: Test with Catch2
        run: ./build/tests/tests
        
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -B build

      - name: Build
        run: cmake --build build
